GET http://localhost:3001/posts


###

GET http://localhost:3001/comments?postParentID=65f34ff57b35401cef25749c


###

POST http://localhost:3001/posts
Content-Type: application/json

{   "author": "Jidáš",
    "text": "Babiš ven!"
}

###

POST http://localhost:3001/comments
Content-Type: application/json

{   "author": "Lenka",
    "text": "Order burgir",
    "postParentID": "65f34ff57b35401cef25749c"
}

###

DELETE http://localhost:3001/todo/delete/65e2130ca0b305fd423b6494

###

PUT http://localhost:3001/todo/complete/65e20a61a0b305fd423b6491